name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:14
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: ecommerce_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Elixir
      uses: actions/setup-elixir@v1
      with:
        otp-version: 24.2.2
        elixir-version: 1.14.3
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
